<a href="https://colab.research.google.com/github/Thalapathi26/AI_ML/blob/main/FNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('/content/personality_datasert.csv')

In [ ]:
df

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,4.0,No,4.0,6.0,No,13.0,5.0,Extrovert
1,9.0,Yes,0.0,0.0,Yes,0.0,3.0,Introvert
2,9.0,Yes,1.0,2.0,Yes,5.0,2.0,Introvert
3,0.0,No,6.0,7.0,No,14.0,8.0,Extrovert
4,3.0,No,9.0,4.0,No,8.0,5.0,Extrovert
...,...,...,...,...,...,...,...,...
2895,3.0,No,7.0,6.0,No,6.0,6.0,Extrovert
2896,3.0,No,8.0,3.0,No,14.0,9.0,Extrovert
2897,4.0,Yes,1.0,1.0,Yes,4.0,0.0,Introvert
2898,11.0,Yes,1.0,3.0,Yes,2.0,0.0,Introvert
2899,3.0,No,6.0,6.0,No,6.0,9.0,Extrovert

In [ ]:
df.isnull().sum()

Time_spent_Alone             0
Stage_fear                   0
Social_event_attendance      0
Going_outside                0
Drained_after_socializing    0
Friends_circle_size          0
Post_frequency               0
Personality                  0
dtype: int64

In [ ]:

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
for i in df.columns:
  if df[i].dtype=='float64':
    df[i]=sc.fit_transform(df[[i]])

In [ ]:
df.head()

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,-0.147014,No,0.012759,1.350613,No,1.590680,0.496104,Extrovert
1,1.306226,Yes,-1.379944,-1.350613,Yes,-1.481437,-0.195199,Introvert
2,1.306226,Yes,-1.031768,-0.450204,Yes,-0.299853,-0.540850,Introvert
3,-1.309607,No,0.709111,1.800817,No,1.826996,1.533059,Extrovert
4,-0.437663,No,1.753638,0.450204,No,0.409096,0.496104,Extrovert

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in df.columns:
  if df[i].dtype=='object':
    df[i]=le.fit_transform(df[i])
df.head()

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,-0.147014,0,0.012759,1.350613,0,1.590680,0.496104,0
1,1.306226,1,-1.379944,-1.350613,1,-1.481437,-0.195199,1
2,1.306226,1,-1.031768,-0.450204,1,-0.299853,-0.540850,1
3,-1.309607,0,0.709111,1.800817,0,1.826996,1.533059,0
4,-0.437663,0,1.753638,0.450204,0,0.409096,0.496104,0

In [ ]:
x=df.drop('Personality',axis=1)
y=df['Personality']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=52)

In [ ]:
import tensorflow as tf

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
model=Sequential([
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
fnn=model.fit(x_train,y_train,epochs=100,batch_size=32,verbose=1)

Epoch 1/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9043 - loss: 0.3689
Epoch 2/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2686
Epoch 3/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9336 - loss: 0.2616
Epoch 4/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2526
Epoch 5/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9336 - loss: 0.2473
Epoch 6/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2415
Epoch 7/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9336 - loss: 0.2359
Epoch 8/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9336 - loss: 0.2323
Epoch 9/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2309
Epoch 10/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2290
Epoch 11/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2252
Epoch 12/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2234
Epoch 13/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2218
Epoch 14/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2218
Epoch 15/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2195
Epoch 16/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2179
Epoch 17/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2191
Epoch 18/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2172
Epoch 19/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2144
Epoch 20/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2149
Epoch 21/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9336 - loss: 0.2139
Epoch 22/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2129
Epoch 23/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9336 - loss: 0.2132
Epoch 24/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2137
Epoch 25/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2121
Epoch 26/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9336 - loss: 0.2136
Epoch 27/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9336 - loss: 0.2112
Epoch 28/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9336 - loss: 0.2105
Epoch 29/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9336 - loss: 0.2102
Epoch 30/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9336 - loss: 0.2098
Epoch 31/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9336 - loss: 0.2103
Epoch 32/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9336 - loss: 0.2105
Epoch 33/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2093
Epoch 34/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2089
Epoch 35/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2088
Epoch 36/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2078
Epoch 37/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2082
Epoch 38/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2076
Epoch 39/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2068
Epoch 40/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2056
Epoch 41/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2055
Epoch 42/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2077
Epoch 43/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2081
Epoch 44/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2085
Epoch 45/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2048
Epoch 46/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2069
Epoch 47/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2062
Epoch 48/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9336 - loss: 0.2061
Epoch 49/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9336 - loss: 0.2042
Epoch 50/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2057
Epoch 51/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9336 - loss: 0.2046
Epoch 52/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2051
Epoch 53/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9336 - loss: 0.2048
Epoch 54/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2053
Epoch 55/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2040
Epoch 56/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2049
Epoch 57/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9336 - loss: 0.2037
Epoch 58/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9332 - loss: 0.2043
Epoch 59/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2027
Epoch 60/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2018
Epoch 61/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9336 - loss: 0.2021
Epoch 62/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9336 - loss: 0.2020
Epoch 63/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2016
Epoch 64/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2018
Epoch 65/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9336 - loss: 0.2017
Epoch 66/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2024
Epoch 67/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9341 - loss: 0.2007
Epoch 68/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9341 - loss: 0.2017
Epoch 69/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9341 - loss: 0.2013
Epoch 70/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9341 - loss: 0.1991
Epoch 71/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.2002
Epoch 72/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9341 - loss: 0.1997
Epoch 73/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9341 - loss: 0.2013
Epoch 74/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9341 - loss: 0.1981
Epoch 75/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9341 - loss: 0.1981
Epoch 76/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9341 - loss: 0.2000
Epoch 77/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9341 - loss: 0.1987
Epoch 78/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9341 - loss: 0.1971
Epoch 79/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9341 - loss: 0.1997
Epoch 80/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9341 - loss: 0.1966
Epoch 81/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9341 - loss: 0.1968
Epoch 82/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9341 - loss: 0.1971
Epoch 83/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9341 - loss: 0.1974
Epoch 84/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9341 - loss: 0.1960
Epoch 85/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9341 - loss: 0.1945
Epoch 86/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9341 - loss: 0.1977
Epoch 87/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9341 - loss: 0.1947
Epoch 88/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9341 - loss: 0.1974
Epoch 89/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9341 - loss: 0.1951
Epoch 90/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9341 - loss: 0.1956
Epoch 91/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9341 - loss: 0.1951
Epoch 92/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9341 - loss: 0.1948
Epoch 93/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9336 - loss: 0.1956
Epoch 94/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9341 - loss: 0.1961
Epoch 95/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9341 - loss: 0.1942
Epoch 96/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9341 - loss: 0.1944
Epoch 97/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9341 - loss: 0.1932
Epoch 98/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9341 - loss: 0.1930
Epoch 99/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9341 - loss: 0.1941
Epoch 100/100
73/73 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9341 - loss: 0.1946

In [ ]:
y_pred=model.predict(x_test)
y_pred

19/19 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step

array([[9.96199250e-01],
       [7.05891941e-03],
       [1.55093353e-02],
       [8.67121041e-01],
       [7.84928441e-01],
       [6.51620552e-02],
       [1.09925484e-02],
       [9.92533565e-01],
       [9.14135831e-04],
       [4.05361038e-03],
       [9.77055967e-01],
       [1.27905920e-01],
       [1.28439367e-02],
       [8.58961046e-01],
       [2.30223988e-03],
       [2.91400589e-02],
       [1.84262414e-02],
       [6.91343993e-02],
       [9.51100409e-01],
       [3.22003625e-02],
       [9.19899106e-01],
       [3.58974584e-03],
       [9.89624023e-01],
       [9.36071634e-01],
       [6.41332287e-03],
       [3.29609215e-02],
       [9.72743571e-01],
       [8.36387575e-01],
       [9.78513181e-01],
       [1.58223358e-03],
       [9.55410302e-01],
       [8.58454645e-01],
       [3.35256666e-01],
       [9.42173302e-01],
       [9.81198549e-01],
       [9.80129063e-01],
       [2.56152940e-04],
       [8.37792993e-01],
       [4.15131217e-03],
       [1.38134070e-04],
       [9.55193162e-01],
       [9.93072629e-01],
       [4.67035770e-02],
       [2.08887737e-03],
       [1.28752207e-02],
       [8.93344998e-01],
       [9.71319973e-01],
       [3.79686127e-04],
       [9.88873363e-01],
       [2.50949234e-01],
       [9.65836406e-01],
       [7.71648645e-01],
       [2.58499570e-03],
       [7.10356608e-02],
       [8.42028558e-01],
       [5.05413627e-03],
       [9.87125099e-01],
       [6.00330867e-02],
       [7.97753513e-04],
       [4.85685691e-02],
       [3.83852224e-04],
       [9.44321096e-01],
       [8.27399015e-01],
       [2.57429224e-03],
       [1.92615427e-02],
       [8.43246937e-01],
       [9.66881096e-01],
       [9.73207951e-01],
       [2.42744029e-01],
       [2.04278350e-01],
       [9.12822634e-02],
       [2.98790690e-02],
       [9.79815185e-01],
       [1.66604981e-01],
       [3.73698443e-01],
       [2.19791755e-02],
       [3.76528502e-03],
       [9.99951243e-01],
       [9.63694692e-01],
       [9.12248373e-01],
       [1.55714855e-01],
       [9.80835319e-01],
       [9.97473001e-01],
       [9.65185761e-01],
       [8.00900578e-01],
       [7.60809705e-03],
       [2.92021066e-01],
       [1.15055963e-03],
       [9.87018168e-01],
       [2.41868161e-02],
       [9.69967663e-01],
       [9.87465739e-01],
       [8.86974454e-01],
       [2.95581818e-01],
       [8.48161757e-01],
       [9.95602846e-01],
       [1.00536486e-02],
       [8.25812761e-03],
       [8.76497865e-01],
       [9.55314457e-01],
       [1.02141649e-02],
       [3.10636926e-02],
       [8.43988776e-01],
       [1.08079950e-03],
       [1.46048721e-02],
       [9.97632504e-01],
       [8.99887085e-03],
       [7.21871197e-01],
       [6.61825910e-02],
       [9.01884317e-01],
       [9.55666840e-01],
       [3.25380899e-02],
       [2.95856618e-03],
       [6.06039166e-03],
       [9.48884010e-01],
       [2.18295187e-01],
       [9.08512831e-01],
       [8.83953810e-01],
       [9.97907698e-01],
       [2.38344539e-02],
       [9.45405483e-01],
       [1.15779400e-01],
       [3.60766472e-03],
       [2.55601525e-01],
       [9.05833781e-01],
       [9.03586626e-01],
       [9.26786900e-01],
       [6.36506639e-03],
       [9.36537981e-01],
       [9.70649064e-01],
       [7.56972507e-02],
       [3.31062138e-01],
       [9.60538089e-01],
       [7.92234540e-02],
       [4.74954577e-04],
       [2.58166827e-02],
       [7.89599001e-01],
       [9.94638622e-01],
       [8.23324144e-01],
       [1.54933836e-02],
       [8.68151486e-02],
       [1.64443906e-02],
       [1.44857258e-01],
       [1.24365734e-02],
       [9.80030477e-01],
       [1.42350867e-02],
       [2.36252099e-02],
       [9.70270872e-01],
       [4.44780057e-03],
       [5.66949584e-02],
       [9.02835071e-01],
       [9.31044854e-03],
       [8.62043500e-01],
       [8.40181768e-01],
       [6.62238672e-02],
       [5.04272915e-02],
       [9.74730074e-01],
       [9.93723691e-01],
       [2.30305821e-01],
       [5.07039065e-03],
       [9.64691520e-01],
       [9.93822098e-01],
       [7.32617378e-01],
       [9.13639009e-01],
       [9.78530198e-02],
       [2.66728643e-03],
       [8.54616538e-02],
       [9.44101989e-01],
       [9.28371012e-01],
       [8.75227690e-01],
       [9.77422237e-01],
       [9.86034036e-01],
       [8.01762845e-03],
       [2.28185020e-03],
       [2.84932345e-01],
       [8.36311579e-01],
       [1.27029028e-02],
       [7.93631494e-01],
       [1.87370822e-01],
       [1.62939042e-01],
       [3.69688496e-02],
       [9.10960376e-01],
       [4.98557203e-02],
       [2.10626240e-04],
       [7.63723850e-01],
       [9.70913112e-01],
       [5.05898194e-03],
       [4.18599695e-02],
       [5.65467738e-02],
       [3.44834104e-03],
       [9.25905257e-02],
       [1.14025466e-01],
       [9.91777599e-01],
       [3.38517427e-02],
       [1.35049865e-01],
       [2.69857533e-02],
       [9.93749499e-01],
       [4.15505543e-02],
       [7.15619251e-02],
       [8.02268803e-01],
       [8.67616713e-01],
       [9.67129469e-01],
       [3.23798647e-03],
       [9.44054902e-01],
       [9.70166981e-01],
       [5.15608527e-02],
       [8.43067467e-03],
       [9.75076973e-01],
       [1.57727525e-02],
       [9.69621956e-01],
       [1.27032558e-02],
       [9.89031076e-01],
       [1.49159040e-02],
       [1.87238175e-02],
       [2.92544290e-02],
       [1.09988116e-02],
       [8.04858387e-01],
       [8.84247780e-01],
       [8.84024680e-01],
       [2.98863952e-03],
       [9.09732044e-01],
       [1.54943150e-02],
       [8.51781011e-01],
       [8.78413737e-01],
       [4.49333666e-03],
       [9.98582721e-01],
       [2.70800162e-02],
       [9.39378738e-01],
       [9.18046176e-01],
       [1.73309986e-02],
       [2.21068520e-04],
       [9.45137024e-01],
       [9.53324854e-01],
       [6.26482419e-04],
       [9.44286525e-01],
       [4.04427461e-02],
       [2.87701352e-03],
       [9.94333029e-01],
       [2.37330236e-02],
       [8.65238547e-01],
       [9.51896548e-01],
       [9.01725888e-03],
       [9.05216157e-01],
       [1.61975831e-01],
       [9.14079417e-03],
       [9.68982339e-01],
       [8.98595989e-01],
       [3.73286218e-03],
       [1.44017726e-01],
       [9.78365898e-01],
       [9.79001760e-01],
       [7.42268860e-02],
       [9.77198362e-01],
       [9.65064168e-01],
       [1.02341823e-01],
       [9.25531268e-01],
       [9.98695672e-01],
       [3.58321588e-03],
       [6.75068516e-03],
       [5.23958467e-02],
       [9.75072324e-01],
       [8.34940672e-01],
       [7.36468937e-03],
       [9.52076197e-01],
       [9.86128092e-01],
       [4.90175560e-02],
       [9.75891769e-01],
       [9.90758002e-01],
       [2.98200492e-02],
       [9.82737482e-01],
       [6.16612087e-04],
       [8.83811831e-01],
       [3.40926260e-01],
       [1.69735309e-02],
       [4.80591465e-04],
       [1.25463018e-02],
       [9.84964728e-01],
       [5.04272915e-02],
       [2.90248059e-02],
       [7.59350136e-04],
       [8.91208589e-01],
       [9.35277581e-01],
       [1.86382532e-01],
       [9.84187067e-01],
       [9.96582747e-01],
       [9.80686188e-01],
       [9.38680256e-04],
       [9.77567315e-01],
       [9.52963889e-01],
       [5.68550676e-02],
       [1.42190829e-02],
       [8.67686421e-03],
       [1.38335779e-01],
       [4.60946321e-01],
       [2.48526782e-03],
       [8.43988776e-01],
       [5.78326657e-02],
       [1.63166169e-02],
       [9.63886559e-01],
       [2.96111792e-01],
       [9.79268312e-01],
       [7.18771294e-03],
       [3.86087820e-02],
       [9.86119270e-01],
       [9.42387879e-01],
       [9.55137551e-01],
       [9.98615801e-01],
       [4.52821925e-02],
       [9.77549851e-01],
       [9.50923026e-01],
       [2.61849552e-01],
       [1.34589262e-02],
       [1.93506226e-01],
       [6.14007981e-03],
       [1.26950350e-02],
       [7.81398356e-01],
       [1.74747128e-02],
       [1.10885829e-01],
       [9.63224471e-01],
       [2.33543627e-02],
       [1.06118887e-03],
       [8.38794291e-01],
       [9.35245991e-01],
       [2.44789920e-03],
       [2.06305573e-04],
       [8.14983964e-01],
       [2.01756153e-02],
       [2.57320795e-02],
       [1.19892269e-01],
       [5.78832114e-03],
       [3.33692543e-02],
       [4.37964760e-02],
       [3.22757512e-01],
       [7.54663115e-03],
       [9.49029446e-01],
       [9.18756783e-01],
       [1.57617256e-02],
       [9.97823894e-01],
       [9.81231451e-01],
       [6.18920587e-02],
       [9.86138940e-01],
       [9.07337725e-01],
       [7.05148935e-01],
       [9.95218217e-01],
       [2.80281812e-01],
       [6.08110353e-02],
       [1.06347166e-03],
       [3.96574326e-02],
       [6.15521111e-02],
       [3.31578016e-01],
       [8.31857681e-01],
       [8.81949663e-01],
       [7.54643837e-03],
       [9.86365557e-01],
       [8.79936635e-01],
       [4.05747145e-02],
       [7.91258514e-01],
       [9.44858313e-01],
       [2.05679834e-02],
       [8.62938344e-01],
       [9.24792528e-01],
       [1.78963635e-02],
       [4.35913447e-03],
       [9.85095382e-01],
       [4.99219215e-03],
       [9.31449771e-01],
       [3.89789306e-02],
       [8.73202860e-01],
       [8.88488054e-01],
       [8.30734074e-01],
       [1.97837297e-02],
       [9.76636112e-02],
       [9.07574296e-01],
       [8.44717205e-01],
       [1.78486705e-02],
       [9.69529927e-01],
       [9.75646496e-01],
       [3.29907537e-02],
       [9.31281686e-01],
       [8.25521290e-01],
       [9.62335765e-01],
       [8.24663758e-01],
       [9.74368513e-01],
       [7.90951848e-02],
       [2.95723647e-01],
       [1.12627745e-02],
       [8.15431774e-01],
       [7.75681296e-03],
       [8.94113123e-01],
       [2.95005436e-03],
       [9.98478293e-01],
       [2.21320510e-01],
       [3.81022017e-03],
       [9.06520844e-01],
       [9.86594915e-01],
       [7.86683410e-02],
       [4.56371671e-03],
       [4.30835038e-02],
       [9.34316516e-01],
       [9.41428661e-01],
       [1.32628396e-01],
       [8.62611234e-01],
       [1.18983528e-02],
       [4.13051881e-02],
       [3.98813980e-03],
       [1.03805289e-02],
       [9.76165175e-01],
       [8.37792993e-01],
       [9.49436843e-01],
       [9.70600545e-01],
       [9.93002534e-01],
       [2.52020862e-02],
       [8.00900578e-01],
       [9.98021126e-01],
       [9.60096657e-01],
       [3.67772989e-02],
       [9.92151260e-01],
       [9.52987373e-01],
       [9.66258526e-01],
       [2.47282282e-01],
       [9.01077017e-02],
       [8.15693736e-01],
       [7.01769769e-01],
       [2.00420395e-01],
       [9.54485655e-01],
       [5.31834143e-04],
       [9.84368861e-01],
       [9.95100825e-04],
       [1.22905790e-03],
       [4.82586771e-02],
       [9.75755453e-01],
       [5.19973645e-03],
       [5.15591295e-04],
       [2.09492862e-01],
       [6.41332287e-03],
       [9.75242853e-01],
       [8.70217443e-01],
       [5.18358138e-04],
       [6.72886595e-02],
       [1.05219334e-02],
       [1.33489911e-02],
       [3.81743424e-02],
       [9.76932466e-01],
       [9.97134686e-01],
       [3.97618307e-04],
       [9.31825023e-03],
       [1.87699136e-03],
       [3.70192080e-04],
       [9.87139165e-01],
       [8.15693736e-01],
       [1.52262463e-03],
       [8.40181768e-01],
       [3.46622281e-02],
       [1.21777421e-02],
       [8.38653028e-01],
       [8.22040379e-01],
       [9.97941494e-01],
       [5.94485030e-02],
       [1.26190007e-01],
       [8.83811831e-01],
       [9.76752162e-01],
       [8.60129669e-02],
       [6.90696299e-01],
       [8.62123370e-01],
       [9.10960376e-01],
       [6.69653118e-02],
       [4.62151191e-04],
       [1.83842916e-04],
       [9.37050164e-01],
       [9.53705516e-03],
       [9.48077977e-01],
       [9.95346606e-01],
       [5.36252221e-04],
       [8.15693736e-01],
       [1.51221417e-02],
       [3.06860674e-02],
       [3.79360514e-04],
       [2.75587365e-02],
       [9.33629453e-01],
       [8.68780613e-01],
       [1.35773085e-02],
       [9.70714986e-01],
       [8.99884641e-01],
       [8.33693981e-01],
       [4.13779467e-02],
       [1.43906726e-02],
       [2.83618011e-02],
       [9.53324854e-01],
       [8.43179151e-02],
       [3.14680263e-02],
       [9.79654431e-01],
       [8.84576321e-01],
       [9.73827183e-01],
       [1.00885900e-02],
       [2.73810830e-02],
       [1.44277271e-02],
       [8.57373297e-01],
       [1.23841669e-02],
       [9.29023884e-03],
       [1.49035547e-02],
       [4.73174127e-03],
       [1.11231385e-02],
       [9.68806684e-01],
       [9.16456044e-01],
       [3.87484254e-03],
       [9.93096411e-01],
       [1.31814843e-02],
       [9.29102838e-01],
       [1.73530832e-01],
       [4.03246284e-03],
       [3.28885764e-03],
       [8.24911416e-01],
       [2.51828402e-01],
       [9.54035103e-01],
       [3.36167030e-03],
       [9.41555679e-01],
       [9.82927382e-01],
       [7.69614398e-01],
       [3.95269841e-01],
       [8.83811831e-01],
       [3.69356126e-02],
       [7.61872507e-04],
       [9.85136926e-01],
       [9.44856882e-01],
       [9.76551414e-01],
       [9.03745353e-01],
       [2.31268369e-02],
       [9.52198982e-01],
       [8.89340937e-01],
       [9.78952587e-01],
       [8.75422597e-01],
       [9.87782419e-01],
       [8.77197921e-01],
       [9.42307413e-01],
       [2.64623929e-02],
       [9.58885670e-01],
       [7.59192184e-02],
       [6.12359680e-03],
       [9.05156791e-01],
       [9.01388526e-01],
       [1.93029288e-02],
       [2.88405102e-02],
       [9.76077795e-01],
       [9.96630847e-01],
       [9.29753125e-01],
       [9.50839043e-01],
       [9.77001607e-01],
       [8.51647913e-01],
       [9.74278212e-01],
       [3.46373431e-02],
       [9.11233425e-01],
       [3.02041993e-02],
       [5.29949379e-04],
       [8.44717205e-01],
       [8.77528369e-01],
       [8.40514824e-02],
       [8.25521290e-01],
       [4.94579151e-02],
       [1.02341823e-01],
       [3.58833581e-01],
       [9.70649064e-01],
       [8.41071546e-01],
       [2.39275411e-01],
       [9.80019033e-01],
       [9.49063778e-01],
       [9.75456119e-01],
       [9.97194767e-01],
       [2.82584012e-01],
       [8.44577014e-01],
       [7.44044006e-01],
       [9.40174878e-01],
       [9.93103445e-01],
       [9.86852586e-01],
       [9.01388526e-01],
       [2.41784543e-01],
       [9.88278270e-01],
       [8.94635636e-03],
       [9.82643306e-01],
       [9.67881441e-01],
       [9.89221215e-01]], dtype=float32)